--  find customers who have not placed any orders
select c.FirstName, c.LastName, c.Email 
from Customers c
where c.CustomerID not in (select distinct CustomerID from Orders);

--  find the total number of products available for sale
select count(*) as TotalProducts from Products;

--  calculate the total revenue generated by TechShop
select sum(TotalAmount) as TotalRevenue from Orders;

-- calculate the average quantity ordered for products in a specific category
select avg(od.Quantity) as avg_quantity_ordered
from OrderDetails od
join Products p on od.ProductID = p.ProductID
join Categories c on p.CategoryID = c.CategoryID
where c.CategoryName = 'YourCategoryName';


--  calculate the total revenue generated by a specific customer
select sum(o.TotalAmount) as CustomerTotalRevenue
from Orders o
where o.CustomerID = 3;

--  find the customers who have placed the most orders
select c.FirstName, c.LastName, count(o.OrderID) as OrderCount
from Customers c
join Orders o on c.CustomerID = o.CustomerID
group by c.CustomerID
order by OrderCount desc
limit 1;

--  find the most popular product category (highest total quantity ordered)
select c.CategoryName, sum(od.Quantity) as TotalQuantityOrdered
from OrderDetails od
join Products p on od.ProductID = p.ProductID
join Categories c on p.CategoryID = c.CategoryID
group by c.CategoryName
order by TotalQuantityOrdered desc
limit 1;

--  find the customer who has spent the most money on electronic gadgets
select c.FirstName, c.LastName, sum(o.TotalAmount) as TotalSpent
from Customers c
join Orders o on c.CustomerID = o.CustomerID
where c.CustomerID in (
    select distinct o.CustomerID
    from Orders o
    join OrderDetails od on o.OrderID = od.OrderID
    join Products p on od.ProductID = p.ProductID
    join Categories cat on p.CategoryID = cat.CategoryID
    where cat.CategoryName = 'Electronics'
)
group by c.CustomerID
order by TotalSpent desc
limit 1;

-- calculate the average order value (total revenue / total orders)
select avg(TotalAmount) as AverageOrderValue from Orders;

-- find the total number of orders placed by each customer
select c.FirstName, c.LastName, count(o.OrderID) as OrderCount
from Customers c
left join Orders o on c.CustomerID = o.CustomerID
group by c.CustomerID;
